In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.cluster.hierarchy as shc
from sklearn.preprocessing import normalize

In [2]:
dataframe = pd.read_csv("/Users/migherize/SourceTree/Insights_chess/src/Data_enginner/output/Cluster.csv")
dataframe.head()

,Jugador,Partidas,Victoria Blancas,Tablas Blancas,Perdidas Blancas,Victorias Negras,Tablas Negras,Perdidas Negras
0,danielbarreto,17113,4769,283,3713,4548,290,3510
1,jhoseim_torres,20,1,0,8,0,1,10
2,mherize,4060,1063,96,899,1042,99,861
3,rirr2020,894,205,5,266,179,5,234
4,juandv12,2847,655,88,687,678,57,682